diff --git a/scull/Makefile b/scull/Makefile
index 3f6c8d0..2fc13cc 100644
--- a/scull/Makefile
+++ b/scull/Makefile
@@ -23,12 +23,15 @@ obj-m       := scull.o
 
 else
 
-KERNELDIR ?= /lib/modules/$(shell uname -r)/build
+KERNELDIR ?= ${KERNEL_SRC}
 PWD       := $(shell pwd)
 
 modules:
        $(MAKE) -C $(KERNELDIR) M=$(PWD) modules
 
+modules_install:
+       $(MAKE) -C $(KERNELDIR) M=$(PWD) modules_install
+
 endif
 
