diff --git a/Makefile b/Makefile
index 91be7cf..04ba6e1 100644
--- a/Makefile
+++ b/Makefile
@@ -12,7 +12,7 @@ ifeq ($(KERNELRELEASE),)
 
     # Assume the source tree is where the running kernel was built
     # You should set KERNELDIR in the environment if it's elsewhere
-    KERNELDIR ?= /lib/modules/$(shell uname -r)/build
+    KERNELDIR ?= ${KERNEL_SRC}
     # The current directory is passed to sub-makes as argument
     PWD := $(shell pwd)
